dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    my-dashboard:
      file: /tmp/dashboards/dashboard.json

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      url: http://tempo.monitoring.svc.cluster.local:3100
      basicAuth: false
      version: 1
      editable: false
      apiVersion: 1
      uid: tempo
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    searchNamespace: ALL

adminPassword: admin

service:
  type: NodePort

